### ISSUE TITLE
Submodule does not exist

### ISSUE THREAD

**Issue by ajberlier** [gizatt/pydrake_rgbd_sim#1]
It is pointing to ChristopherSweeny which is no longer a github user it looks like. https://github.com/gizatt/DepthSim is likely the intended submodule. Is that correct? I will try this.

**Comment by gizatt** [comment]
Instead of this repo, I'd suggest checking out [this one](https://github.com/ChristopherSweeney/RGBD_SIM), which looks like it achieves the same functionality but was maintained a lot more recently. It looks like he consolidated the now-dead repo at the submodule reference directly into that repo.
